source 'https://rubygems.org'
ruby '2.1.0'
gem 'rails', '4.0.2'
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'foundation-icons-sass-rails'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'cancan'
gem 'devise'
gem 'devise_invitable'
gem 'figaro'
gem 'foundation-rails'
gem 'mysql2'
gem 'rolify'
gem 'simple_form'
gem 'omniauth-facebook'
gem 'pundit'
group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
  gem 'hub', :require=>nil
  gem 'quiet_assets'
  gem 'rails_layout'
end
